### ISSUE TITLE
compilation problems with latest G++

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#668]
ugh looks like another issue in LLVM

```regehr@home:~/alive2/build$ ninja -j1
[3/22] Building CXX object CMakeFiles/llvm_util.dir/llvm_util/known_fns.cpp.o
FAILED: CMakeFiles/llvm_util.dir/llvm_util/known_fns.cpp.o 
/home/regehr/gcc-install/bin/g++   -I../ -I. -I/home/regehr/llvm-project/llvm/include -I/home/regehr/llvm-project/for-alive/include -Wall -Werror -march=native -fPIC  -O3 -O3    -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++2a -MD -MT CMakeFiles/llvm_util.dir/llvm_util/known_fns.cpp.o -MF CMakeFiles/llvm_util.dir/llvm_util/known_fns.cpp.o.d -o CMakeFiles/llvm_util.dir/llvm_util/known_fns.cpp.o -c ../llvm_util/known_fns.cpp
In file included from /home/regehr/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:15,
                 from /home/regehr/llvm-project/llvm/include/llvm/ADT/APFloat.h:20,
                 from /home/regehr/llvm-project/llvm/include/llvm/IR/Constants.h:23,
                 from ../llvm_util/known_fns.cpp:8:
/home/regehr/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1823:18: error: expected unqualified-id before ‘const’
 1823 |   result_pair<R>(const result_pair<R> &Other)
      |                  ^~~~~
/home/regehr/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1823:18: error: expected ‘)’ before ‘const’
 1823 |   result_pair<R>(const result_pair<R> &Other)
      |                 ~^~~~~
      |                  )
/home/regehr/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1873:22: error: expected unqualified-id before ‘const’
 1873 |   enumerator_iter<R>(const enumerator_iter<R> &Other) : Result(Other.Result) {}
      |                      ^~~~~
/home/regehr/llvm-project/llvm/include/llvm/ADT/STLExtras.h:1873:22: error: expected ‘)’ before ‘const’
 1873 |   enumerator_iter<R>(const enumerator_iter<R> &Other) : Result(Other.Result) {}
      |                     ~^~~~~
      |                      )
ninja: build stopped: subcommand failed.
regehr@home:~/alive2/build$ 
```

**Comment by nunoplopes** [comment]
John says all works fine on ubuntu 20.10, so he doesn't care anymore.
