### ISSUE TITLE
Compile error: ‘PtrToAddr’ is not a member of ‘llvm::Instruction’

### ISSUE THREAD

**Issue by Dreamerxic** [AliveToolkit/alive2#1259]
I try to build alive2 with llvm 21.1.6 built from the llvm-project repo.
```
git clone https://github.com/AliveToolkit/alive2.git
cd alive2
mkdir build
cd build
cmake -GNinja -DCMAKE_PREFIX_PATH=/home/dxic/llvmlearn/llvm-project/llvm/build -DBUILD_TV=1 -DCMAKE_BUILD_TYPE=Release ..
ninja
```
A compiler error occured.
```
FAILED: CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o 
/usr/bin/c++  -I/home/dxic/llvmtest/alive2 -I/home/dxic/llvmtest/alive2/build -I/home/dxic/llvmlearn/llvm-project/llvm/include -I/home/dxic/llvmlearn/llvm-project/llvm/build/include -Wall -Werror -fPIC -fstrict-enums  -O3 -O3  -std=c++20   -D_GNU_SOURCE -D_DEBUG -D_GLIBCXX_ASSERTIONS -DEXPERIMENTAL_KEY_INSTRUCTIONS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MT CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o -MF CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o.d -o CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o -c /home/dxic/llvmtest/alive2/llvm_util/llvm2alive.cpp
/home/dxic/llvmtest/alive2/llvm_util/llvm2alive.cpp: In member function ‘{anonymous}::llvm2alive_::RetTy {anonymous}::llvm2alive_::visitCastInst(llvm::CastInst&)’:
/home/dxic/llvmtest/alive2/llvm_util/llvm2alive.cpp:297:31: error: ‘PtrToAddr’ is not a member of ‘llvm::Instruction’
  297 |       case llvm::Instruction::PtrToAddr: op = ConversionOp::Ptr2Addr; break;
      |                               ^~~~~~~~~
```

**Comment by Dreamerxic** [comment]
@nunoplopes However, llvm 21.1.6 is the latest version. That is weird.

The released version alive2-21.0 is OK to work with llvm 21.1.6, except that I have to initialize the .git for alive2-21.0.
