### ISSUE TITLE
can't build in Debug mode using g++ 9.3.0

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#526]
```
/usr/bin/c++   -I../ -I. -I/home/regehr/llvm-project/llvm/include -I/home/regehr/llvm-project/for-alive/include -Wall -Werror -march=native -fPIC  -g -Og -g   -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -std=c++17 -MD -MT CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o -MF CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o.d -o CMakeFiles/llvm_util.dir/llvm_util/llvm2alive.cpp.o -c ../llvm_util/llvm2alive.cpp
In file included from /home/regehr/llvm-project/llvm/include/llvm/IR/InstrTypes.h:24,
                 from /home/regehr/llvm-project/llvm/include/llvm/Analysis/ValueTracking.h:22,
                 from ../llvm_util/llvm2alive.cpp:8:
/home/regehr/llvm-project/llvm/include/llvm/ADT/Twine.h: In static member function ‘static _Res std::_Function_handler<_Res(_ArgTypes ...), _Functor>::_M_invoke(const std::_Any_data&, _ArgTypes&& ...) [with _Res = IR::Value*; _Functor = {anonymous}::llvm2alive_::get_operand(llvm::Value*)::<lambda(auto:22)>; _ArgTypes = {llvm::ConstantExpr*}]’:
/home/regehr/llvm-project/llvm/include/llvm/ADT/Twine.h:232:16: error: ‘<anonymous>.llvm::Twine::RHS.llvm::Twine::Child::twine’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  232 |           !RHS.twine->isBinary())
      |            ~~~~^~~~~
cc1plus: all warnings being treated as errors
[61/77] Building CXX object CMakeFiles/alive2.dir/llvm_util/llvm2alive.cpp.o

**Comment by regehr** [comment]
building using clang++ works fine

**Comment by regehr** [comment]
ah, nevermind, let's wait for upstream to fix, I'll use clang in the meantime

**Comment by nunoplopes** [comment]
see patch here: https://github.com/AliveToolkit/alive2/issues/494
